  language: python
  cache: pip3
  python:
    - "3.6"

  jobs:
    include:
      - stage: "Init"
        script:
          - cd ORengine/
          - pip3 install -r requirements.txt
      - stage: "Test"
        script:
          - python3 -m unittest -v TrainingDataConsistencyTest
      - stage: "Deploy"
        if: branch = master
        script:
          - echo "Deloy stage"